spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.database}
    password: ${database.password}
    username: ${database.user}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    properties:
      enable_lazy_load_no_trans: true


database:
  host: localhost
  port: 5433
  user: postgres
  password: root123
  database: security_test

  data:
    jpa:
      repositories:
        enabled: true
server:
  port: 9696
  address: localhost

